### ISSUE TITLE
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet

### ISSUE THREAD

**Issue by pbdeuchler** [agconti/cookiecutter-django-rest#131]
I'm getting this error on a brand new project with no changes whatsoever. Googling doesn't seem to return anything, thought I'd ask here. I've dealt with the `Models aren't loaded yet` error but never seen this before.

``` python
(ecosystem) → python test/manage.py runserver
Traceback (most recent call last):
  File "test/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/philipdeuchler/.virtualenvs/ecosystem/lib/python3.5/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/Users/philipdeuchler/.virtualenvs/ecosystem/lib/python3.5/site-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/philipdeuchler/.virtualenvs/ecosystem/lib/python3.5/site-packages/django/core/management/__init__.py", line 176, in fetch_command
    commands = get_commands()
  File "/Users/philipdeuchler/.virtualenvs/ecosystem/lib/python3.5/site-packages/django/core/management/__init__.py", line 71, in get_commands
    for app_config in reversed(list(apps.get_app_configs())):
  File "/Users/philipdeuchler/.virtualenvs/ecosystem/lib/python3.5/site-packages/django/apps/registry.py", line 137, in get_app_configs
    self.check_apps_ready()
  File "/Users/philipdeuchler/.virtualenvs/ecosystem/lib/python3.5/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

**Comment by pbdeuchler** [comment]
I get this error when trying to import the settings class from the command line:

``` python
>>> from config.local import Local
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/philipdeuchler/Dropbox/workspace/testtest-django/test/config/__init__.py", line 3, in <module>
    from .local import Local  # noqa
  File "/Users/philipdeuchler/Dropbox/workspace/testtest-django/test/config/local.py", line 8, in <module>
    class Local(Common):
  File "/Users/philipdeuchler/.virtualenvs/ecosystem/src/django-configurations-master/configurations/base.py", line 32, in __new__
    raise ImproperlyConfigured(install_failure)
django.core.exceptions.ImproperlyConfigured: django-configurations settings importer wasn't correctly installed. Please use one of the starter functions to install it as mentioned in the docs: http://django-configurations.readthedocs.org/
```

**Comment by pbdeuchler** [comment]
More investigation has turned this up: https://github.com/jazzband/django-configurations/issues/133

**Comment by agconti** [comment]
Hi @pbdeuchler,

Thanks for logging this issue and including your research!

I just did a clean pull and ran the test cases and server and everything worked nicely. Can you clone and run the example project, `piedpiper-web` , at git@github.com:agconti/piedpiper-web.git, and see if it works on your local machine?

Travis would have caught a configuration issue like this so something must have changed with your project. By cloning the example project, we'll be sure that we're both working with the same code base with the same configuration and we'll be able to debug further.

**Comment by agconti** [comment]
Hi @pbdeuchler, 

I've updated the project's django-configurations version since it is now supported by JazzBand, #132. Using this version may solve your issue depending on the what you've included in installed apps. I've kept the `piedpiper-web` demo the same however, so we still have a clean slate to test the original issue in the original configuration. 

I'm going to close this for now, but please open the issue again if the problem persists :smile:!

**Comment by pbdeuchler** [comment]
Can't test on a clean project ATM, but i've upgraded my current project to Django 1.9 and django-configurations 1.0 and it all works! I'll try and test on `piedpiper` later

Thanks for the quick reply and resolution!

**Comment by agconti** [comment]
Awesome! Glad to hear it!

On Tue, Jan 26, 2016 at 3:52 PM, Philip Deuchler notifications@github.com
wrote:

> Can't test on a clean project ATM, but i've upgraded my current one to
> Django 1.9 and django-configurations 1.0 and it all works! I'll try and
> test on piedpiper later
> 
> Thanks for the quick reply and resolution!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/agconti/cookiecutter-django-rest/issues/131#issuecomment-175224439
> .

## 

Andrew Conti

Full Stack Developer

SoHo | NYC

(203) 240-1689 | agconti.com http://www.agconti.com/

**Comment by rustanacexd** [comment]
this bug still happening
