### ISSUE TITLE
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

### ISSUE THREAD

**Issue by rustanacexd** [agconti/cookiecutter-django-rest#522]
I am having this issue. any clue? this is my repo - https://github.com/rustanacexd/go2-product-customizer-api

```2018-01-12T07:31:56.187555+00:00 app[web.1]: raise AppRegistryNotReady("Apps aren't loaded yet.")```
```2018-01-12T07:31:56.187582+00:00 app[web.1]: django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.```

some errors before that - (screenshot - http://take.ms/o4m41)

Very cool starter kit for drf btw! the best I've seen

**Comment by agconti** [comment]
Hey @rustanacexd thanks for opening up an issue! ✨ 

I created a fresh installation from scratch myself and couldn't replicate your issue locally or deployed. Can you share your fresh install? 

I think  some of your changes ion `go2-product-customizer-api` might be the source of your original issue, specifically this [one](https://github.com/rustanacexd/go2-product-customizer-api/commit/d841fd2c48d27a276f22619892134f4f83b95fdb#diff-925533285fae83c2ca206a0bb579c85cR10).

**Comment by rustanacexd** [comment]
ah that! I only added that to try to remedy the issue.  so I made a fresh install without any modifications still got that issue. :( as you can see on my other branch - I don't have that. 

https://github.com/rustanacexd/go2-product-customizer-api/blob/qa/customizer/wsgi.py

Important to note that I am only having the issue when I deployed it on heroku. It works 100% fine locally.

**Comment by agconti** [comment]
no worries!

Are you running your docker container on Herkou?  If the container runs locally  -- then there shouldn't be any difference with running it on Heroku, especially when it comes down to internal django configuration.

**Comment by rustanacexd** [comment]
yes I am running `docker-compose up` when using locally. I am on mac os x using docker-machine

**Comment by agconti** [comment]
Cool -- thats what I'm using. You're using that container on heroku too?

**Comment by rustanacexd** [comment]
yeah everything the same in your cookiecutter. I tried to create a fresh install without any modification. still the same issue :(

**Comment by agconti** [comment]
@rustanacexd yeah -- I just did the same thing but didn't run into any issues. 😢 

Do you have any more info that could help me debug this with you?

**Comment by rustanacexd** [comment]
wait i'll re create a new fresh copy for the last time and see. i'll update you here

**Comment by rustanacexd** [comment]
Unfortunately same error. this is my travis log https://api.travis-ci.org/v3/job/328181417/log.txt

this is my heroku log - 
[herokudebug-prod-logs-1515774248748.txt](https://github.com/agconti/cookiecutter-django-rest/files/1626697/herokudebug-prod-logs-1515774248748.txt)

this is the fresh repo - https://github.com/rustanacexd/heroku-debug

**Comment by rustanacexd** [comment]
this is the fresh repo - https://github.com/rustanacexd/heroku-debug

**Comment by ferndot** [comment]
@agconti I am also facing this error and can provide you access to my source/logs/etc to assist with a solution.

**Comment by agconti** [comment]
@joshua-s thanks for letting me know! Can you also link your project (( if its open source? ))

**Comment by agconti** [comment]
awesome. thanks @joshua-s!

**Comment by rustanacexd** [comment]
I'm glad i'm not the only one with this issue because I'm beginning to think that its because of my machine

**Comment by ferndot** [comment]
@agconti steps to reproduce seem to be:
1. Create a new project from the Cookiecutter
2. Follow the README to setup the project **(ensure that you are using Heroku _free_ dynos)**.
3. Allow the tests to pass and the project to be pushed to Heroku
4. Visit the Heroku app instance and notice the error

I have attached my log:
```
2018-01-21T00:26:13.629475+00:00 heroku[web.1]: Starting process with command `/bin/sh -c ./manage.py\ migrate\ \&\&\ \ \ \ \ ./manage.py\ collectstatic\ --noinput\ \&\&\ \ \ \ \ newrelic-admin\ run-program\ gunicorn\ --bind\ 0.0.0.0:\13556\ --access-logfile\ -\ timestrap.wsgi:application`
2018-01-21T00:26:15.940941+00:00 app[web.1]: Traceback (most recent call last):
2018-01-21T00:26:15.941162+00:00 app[web.1]:   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
2018-01-21T00:26:15.940965+00:00 app[web.1]:   File "./manage.py", line 24, in <module>
2018-01-21T00:26:15.941160+00:00 app[web.1]:     execute_from_command_line(sys.argv)
2018-01-21T00:26:15.941418+00:00 app[web.1]:   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
2018-01-21T00:26:15.941415+00:00 app[web.1]:     utility.execute()
2018-01-21T00:26:15.941662+00:00 app[web.1]:     self.fetch_command(subcommand).run_from_argv(self.argv)
2018-01-21T00:26:15.941664+00:00 app[web.1]:   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 216, in fetch_command
2018-01-21T00:26:15.941864+00:00 app[web.1]:     klass = load_command_class(app_name, subcommand)
2018-01-21T00:26:15.941866+00:00 app[web.1]:   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 36, in load_command_class
2018-01-21T00:26:15.942011+00:00 app[web.1]:     module = import_module('%s.management.commands.%s' % (app_name, name))
2018-01-21T00:26:15.942013+00:00 app[web.1]:   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
2018-01-21T00:26:15.942181+00:00 app[web.1]:     return _bootstrap._gcd_import(name[level:], package, level)
2018-01-21T00:26:15.942183+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
2018-01-21T00:26:15.942350+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
2018-01-21T00:26:15.942442+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
2018-01-21T00:26:15.942532+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
2018-01-21T00:26:15.942623+00:00 app[web.1]:   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
2018-01-21T00:26:15.942752+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2018-01-21T00:26:15.942846+00:00 app[web.1]:   File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 12, in <module>
2018-01-21T00:26:15.942983+00:00 app[web.1]:     from django.db.migrations.autodetector import MigrationAutodetector
2018-01-21T00:26:15.942985+00:00 app[web.1]:   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/autodetector.py", line 11, in <module>
2018-01-21T00:26:15.943121+00:00 app[web.1]:     from django.db.migrations.questioner import MigrationQuestioner
2018-01-21T00:26:15.943123+00:00 app[web.1]:   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/questioner.py", line 9, in <module>
2018-01-21T00:26:15.943255+00:00 app[web.1]:     from .loader import MigrationLoader
2018-01-21T00:26:15.943257+00:00 app[web.1]:   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 8, in <module>
2018-01-21T00:26:15.943392+00:00 app[web.1]:     from django.db.migrations.recorder import MigrationRecorder
2018-01-21T00:26:15.943394+00:00 app[web.1]:   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 9, in <module>
2018-01-21T00:26:15.943525+00:00 app[web.1]:     class MigrationRecorder:
2018-01-21T00:26:15.943527+00:00 app[web.1]:   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 22, in MigrationRecorder
2018-01-21T00:26:15.943661+00:00 app[web.1]:     class Migration(models.Model):
2018-01-21T00:26:15.943858+00:00 app[web.1]:     app_config = apps.get_containing_app_config(module)
2018-01-21T00:26:15.943663+00:00 app[web.1]:   File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 100, in __new__
2018-01-21T00:26:15.944224+00:00 app[web.1]:     raise AppRegistryNotReady("Apps aren't loaded yet.")
2018-01-21T00:26:15.943863+00:00 app[web.1]:   File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 244, in get_containing_app_config
2018-01-21T00:26:15.944249+00:00 app[web.1]: django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
2018-01-21T00:26:15.944064+00:00 app[web.1]:     self.check_apps_ready()
2018-01-21T00:26:15.944069+00:00 app[web.1]:   File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 127, in check_apps_ready
2018-01-21T00:26:16.038478+00:00 heroku[web.1]: Process exited with status 1
2018-01-21T00:26:16.053041+00:00 heroku[web.1]: State changed from starting to crashed
```

**Comment by agconti** [comment]
Hey @rustanacexd and @joshua-s, 

Can you confirm that your heroku apps have an environmental variable called `DJANGO_SECRET`? If so, can you rename it to `DJANGO_SECRET_KEY` and see if your app runs correctly 🎉 ?

**Comment by ferndot** [comment]
@agconti I can confirm that that fixes the issue for me

**Comment by agconti** [comment]
@joshua-s awesome -- thanks for letting me know! ✨

**Comment by Ernestoo777** [comment]
I've got the same issue. I've created my project about 2 weeks ago and only Yesterday it was deployed. How can I fix it?
